@host = https://localhost:7162
@token = PEGA_AQUI_UN_TOKEN_DE_DESARROLLO

GET {{host}}/health
Accept: application/json

###

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "usuario": "TU_USUARIO",
  "password": "TU_PASSWORD_DE_12_O_MAS_CARACTERES"
}

###

GET {{host}}/api/auth/me
Accept: application/json
Authorization: Bearer {{token}}
